### ISSUE TITLE
PCIe config

### ISSUE THREAD

**Issue by TONG-TNG** [MoatLab/FEMU#151]
Is it possible to change NVMe(PCIe) bandwidth of FEMU BBSSD?

**Comment by huaicheng** [comment]
You can achieve so by changing the layout of the bbssd: number of channel and chips, etc. However, FEMU doesn't support emulating precise PCIe link-level bandwidth.

**Comment by TONG-TNG** [comment]
Thank you! So, does that mean there's no PCIe latency between the emulated host and emulated bbSSD when reading/writing in FEMU?

**Comment by huaicheng** [comment]
>So, does that mean there's no data transfer latency through PCIe between the emulated host and emulated bbSSD when reading/writing in FEMU? 

Correct. PCIe latency is much smaller than the Flash and that's FEMU tend to ignore it. 

>Or say the PCIe bandwidth is limited by the qemu host devices?

For such case, probably placing a BW throttler in front of FEMU is what you need.

>Besides, Can I change QEMU_PCI_EXP_LNK_2_5GT to QEMU_PCI_EXP_LNK_16GT and change the link num to change PCIe settings of bbSSD?

You can give it a try and from my understanding, QEMU doesn't really simulate such PCIe-level perf features.

**Comment by TONG-TNG** [comment]
Thank you!
